name: mlb_data_lake

config-version: 2
version: 1.0.0

profile: mlb_data_lake

model-paths: 
  - models

clean-targets:
  - target
  - dbt_packages


models:
  mlb_data_lake:
    staging:
      +materialized: table
      +format: parquet

    marts:
      +materialized: table
      +format: parquet

    analytics:
      +materialized: table
      +format: parquet
