name: 'Deploy to Netlify'

on:
  workflow_dispatch:
    inputs:
      days_ago:
        required: true
        default: 1
  schedule:
    - cron: '0 14 * * *' 

env:
  DATABASE: ${{ secrets.DATABASE }}
  DUCKDB_FILENAME: ${{ secrets.DUCKDB_FILENAME }}
  DUCKDB_GITIGNOREDUCKDB: ${{ secrets.DUCKDB_GITIGNOREDUCKDB }}
  DBT_PROJECT_ROOT: ${{ github.workspace }}/dbt_project
  DBT_SOURCE_DATA_ROOT: s3://zs-mlb-datalake
  DBT_PROFILES_DIR: ${{ github.workspace }}/dbt_project/environment/duckdb0.8.1
  DBT_MOTHERDUCK_TOKEN: ${{ secrets.DBT_MOTHERDUCK_TOKEN }}

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@master
        with:
          python-version: '3.10'

      - name: install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/dbt_project/requirements.txt

      - name: dbt run
        run: |
          export DBT_PROJECT_ROOT=${{ github.workspace }}/dbt_project
          export DBT_SOURCE_DATA_ROOT=s3://zs-mlb-datalake
          export DBT_PROFILES_DIR=${{ github.workspace }}/dbt_project/environment/duckdb0.8.1
          export DBT_MOTHERDUCK_TOKEN=${{ secrets.DBT_MOTHERDUCK_TOKEN }}
          export DBT_DUCKDB_PATH=md:main?motherduck_token=${{ secrets.DBT_MOTHERDUCK_TOKEN }}
          cd ${{ github.workspace }}/dbt_project
          dbt run -t prod
        
      - name: evidence install & build
        run: |	
          cd ${{ github.workspace }}/dbt_project/reports && npm i -force
          cd ${{ github.workspace }}/dbt_project/reports && npm run build

      - name: copy output to working directory
        run: |
          mkdir -p /home/runner/work/_temp/_github_home/build
          cp -r ${{ github.workspace }}/dbt_project/reports/build/* /home/runner/work/_temp/_github_home/build

      - name: Deploy Netlify
        uses: danakim/gh-action-deploy-netlify@master
        with:
          AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          DEPLOY_PROD: true
