name: 'Deploy to Netlify'

on: [workflow_dispatch]

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@master
        with:
          python-version: '3.9'

      - name: install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/ingest/dbt_project/requirements.txt

      - name: dbt run & move files
        run: |
          export DBT_PROJECT_ROOT=${{ github.workspace }}/mlb-data-lake/dbt_project
          export DBT_PROFILES_DIR=${{ github.workspace }}/dbt_project/environment/duckdb0.7
          export DBT_DUCKDB_PATH=${{ github.workspace }}/dbt_project/data/duckdb.db
          dbt run
        