name: 'Deploy to Netlify'

on: [workflow_dispatch]

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@master
        with:
          python-version: '3.9'

      - name: install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/dbt_project/requirements.txt

      - name: dbt run & move files
        run: |
          export DBT_PROJECT_ROOT=${{ github.workspace }}/dbt_project
          export DBT_PROFILES_DIR=${{ github.workspace }}/dbt_project/environment/duckdb0.7
          export DBT_DUCKDB_PATH=${{ github.workspace }}/dbt_project/data/duckdb.db
          cd ${{ github.workspace }}/dbt_project
          dbt run
        
      - name: evidence install & build
        run: |	
          cd ${{ github.workspace }}/dbt_project/reports && npm i -force
          cd ${{ github.workspace }}/dbt_project/reports && mkdir -p data
          cp ${{ github.workspace }}/dbt_project/data/* ${{ github.workspace }}/dbt_project/reports/
          cd ${{ github.workspace }}/dbt_project/reports && npm run build
      
      - name: Deploy Netlify
        uses: danakim/gh-action-deploy-netlify@master
        with:
          AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          DEPLOY_PROD: true